name: C CI

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y gcc
          sudo apt-get install -y cmake
          sudo apt-get install -y cppcheck
          sudo apt-get install -y clang
          sudo apt-get install -y clang-tools

      # this command checks all C files in the current directory and its subdirectories,
      # using the C99 standard, enables all checks, reports inconclusive warnings, checks
      # all preprocessor paths, and returns an error code if any issues are found.
      - name: Run cppcheck
        run: cppcheck --enable=all --inconclusive --force --language=c --std=c99 --error-exitcode=1 .

      - name: Run Clang Static Analyzer
        run: |
          mkdir -p build
          cd build
          cmake ..
          scan-build make

      - name: Compile
        run: |
          mkdir -p build
          cd build
          cmake ..
          make

#      - name: run tests
#        run: ./tests
